services:
  - type: web
    name: cashapp-backend-java
    env: docker
    plan: free
    dockerfilePath: ./server-springboot/Dockerfile
    dockerContext: ./server-springboot
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
